package com.github.se.eduverse.ui.theme

import androidx.compose.material3.ButtonColors
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF099ACC)
val md_theme_light_onPrimary = Color(0xFF000000)
val md_theme_light_primaryContainer = Color(0xFFABF1EA)
val md_theme_light_onPrimaryContainer = Color(0xFF000000)
val md_theme_light_secondary = Color(0xFF0D5ABD)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E5F4)
val md_theme_light_onSecondaryContainer = Color(0xFF0A1E28)
val md_theme_light_tertiary = Color(0xFF000000)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC3E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF71787D)
val md_theme_light_background = Color(0xFFFBFCFF)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_surface = Color(0xFFF8F9FC)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDCE3E9)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_inverseSurface = Color(0xFF2E3133)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1F3)
val md_theme_light_inversePrimary = Color(0xFF7BD0FF)
val md_theme_light_surfaceTint = Color(0xFF00668A)
val md_theme_light_outlineVariant = Color(0xFFC0C7CD)
val md_theme_light_scrim = Color(0xFF000000)
val COLOR_TEXT_PLACEHOLDER = Color(0xFF0D8899).copy(alpha = 0.6f)
val COLOR_CORRECT = Color(0xFF008E21)
val COLOR_INCORRECT = Color(0XFFCC0909)
val md_theme_dark_primary = Color(0xFF7BD0FF)
val md_theme_dark_onPrimary = Color(0xFF003549)
val md_theme_dark_primaryContainer = Color(0xFF004C69)
val md_theme_dark_onPrimaryContainer = Color(0xFFC3E7FF)
val md_theme_dark_secondary = Color(0xFF217384)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_secondaryContainer = Color(0xFF364955)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E5F4)
val md_theme_dark_tertiary = Color(0xFF40FFC0)
val md_theme_dark_onTertiary = Color(0xFF000000)
val md_theme_dark_tertiaryContainer = Color(0xFF108060)
val md_theme_dark_onTertiaryContainer = Color(0xFF000000)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF8B9297)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE1E2E5)
val md_theme_dark_surface = Color(0xFF111416)
val md_theme_dark_onSurface = Color(0xFFC5C6C9)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C7CD)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E5)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inversePrimary = Color(0xFF00668A)
val md_theme_dark_surfaceTint = Color(0xFF7BD0FF)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF008BBB)

fun transparentButtonColor(textColor: Color): ButtonColors {
  return ButtonColors(Color.Transparent, textColor, Color.Transparent, Color.Transparent)
}

val blackTransparentButton = transparentButtonColor(Color.Black)

val blue = ButtonColors(Color(0xFF00A5FF), Color.Black, Color.LightGray, Color.Black)
val orange = ButtonColors(Color(0xFFFFA500), Color.Black, Color.LightGray, Color.Black)
